import type { ProfileId, Review, SourceId } from '@einsatzzeichen/schema';
import { deepFreeze, type DeepReadonly } from './readonly-data.js';

/** Die Person, die am 28. August 2026 fachlich freigegeben hat. */
export const OWNER_DOMAIN_REVIEWER = 'Ruben Vitt';

/** Datum der Sammelfreigabe, ISO wie vom Schema verlangt. */
export const OWNER_DOMAIN_APPROVAL_DATE = '2026-08-28';

/** Der Satz, der die Sammelfreigabe an jedem einzelnen Reviewplatz zurechenbar macht. */
export const OWNER_DOMAIN_APPROVAL_NOTE =
  'Fachlich freigegeben durch den Projektinhaber am 28.08.2026 ' +
  '(Sammelfreigabe im Rahmen von LFH-429).';

/**
 * Ein **frisches** Reviewobjekt der Sammelfreigabe je Aufruf — bewusst eine Fabrik und keine
 * geteilte Konstante: der Ledger führt genau ein eigenes Objekt je Reviewträger, damit ein
 * späteres Einzelvotum nicht über eine gemeinsame Referenz hunderte weitere Einträge mitändert.
 * `domain-reviews.test.ts` nagelt diese Objektidentität fest.
 *
 * `prior` ist eine vorhandene vorbereitende Notiz aus der Bauphase. Sie bleibt erhalten und die
 * Freigabe hängt sich dahinter, statt den Befund zu überschreiben.
 */
export function ownerDomainApproval(prior?: string): Review {
  return {
    status: 'approved',
    reviewer: OWNER_DOMAIN_REVIEWER,
    date: OWNER_DOMAIN_APPROVAL_DATE,
    note: prior === undefined ? OWNER_DOMAIN_APPROVAL_NOTE : `${prior} ${OWNER_DOMAIN_APPROVAL_NOTE}`,
  };
}

/**
 * Fachreview-Ledger des aktuellen Manifests, absichtlich mit genau einem eigenen Objekt je
 * Manifestschlüssel. Dadurch kann ein menschlicher Fachreviewer Einträge schrittweise ändern,
 * ohne über ein gemeinsam referenziertes `Review` versehentlich weitere Einträge mitzuändern.
 *
 * Die Vollständigkeit und die identische Verdrahtung zum Manifest werden in
 * `domain-reviews.test.ts` in beide Richtungen geprüft. Ein neuer Manifest-Eintrag muss deshalb
 * hier bewusst einen eigenen Ledgerplatz bekommen, bevor das Gate wieder grün wird — die
 * Sammelfreigabe vom 28.08.2026 deckt nur, was zu diesem Zeitpunkt im Ledger stand.
 *
 * Die **Fachfragen** je Block stehen seit LFH-430 nicht mehr nur als Kommentar hier, sondern als
 * Daten in `domain-review-questions.ts` (`Q-…`-IDs); `pnpm cli review-dossier` gibt sie je
 * Manifestschlüssel aus. Die Kommentare nennen nur noch die Fragen-IDs. Das Register bleibt nach
 * der Sammelfreigabe stehen: es hält fest, worüber entschieden wurde.
 */
export const MANIFEST_DOMAIN_REVIEWS = deepFreeze({
  'bbk-babz-2025:1.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:1.2#primary': ownerDomainApproval(),
  // Die sechs Grundzeichen aus LFH-424. Fachfragen: Q-1-ereignis-ohne-organisation,
  // Q-1-fahrzeuge-ohne-fahrwerk (`domain-review-questions.ts`).
  'bbk-babz-2025:1.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:1.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:1.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:1.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:1.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:1.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:1.9#primary': ownerDomainApproval(),
  'bbk-babz-2025:1.10#primary': ownerDomainApproval(),
  'bbk-babz-2025:1.11#primary': ownerDomainApproval(),
  'bbk-babz-2025:1.12#primary': ownerDomainApproval(),
  'bbk-babz-2025:1.13#primary': ownerDomainApproval(),
  'bbk-babz-2025:1.14#primary': ownerDomainApproval(),
  'bbk-babz-2025:C.1.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:C.1.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:C.1.3#primary': ownerDomainApproval(),
  // Anhang D.1: alle zehn Darstellungen, je eigener Ledgerplatz. Fachfragen: Q-D.1-*.
  'bbk-babz-2025:D.1.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.1.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.1.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.1.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.1.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.1.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.1.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.1.8#primary': ownerDomainApproval(),
  // D.1.9: die Befundlage aus der Bauphase bleibt als erster Satz der Notiz stehen; die
  // Sammelfreigabe hängt dahinter. Fachfrage: Q-D.1.9-hilfsorganisation-aus-weiss.
  'bbk-babz-2025:D.1.9#primary': ownerDomainApproval(
    'Organisationszuordnung hilfsorganisation ist aus der weißen Fläche abgeleitet.',
  ),
  'bbk-babz-2025:D.1.9#alternative': ownerDomainApproval(
    'Organisationszuordnung hilfsorganisation ist aus der weißen Fläche abgeleitet.',
  ),
  // Anhang D.2: sieben vollständige Ortszeichen, einzeln geführt. Fachfragen: Q-D.2-*.
  'bbk-babz-2025:D.2.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.2.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.2.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.2.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.2.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.2.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.2.7#primary': ownerDomainApproval(),
  // Anhang D.3: dreizehn komponierte Funktionsträger und zwei direkte Kappen; D.3.7 behält
  // sein vorhandenes Reviewobjekt. Fachfragen: Q-D.3-*, Q-D.3.7-zugfuehrer.
  'bbk-babz-2025:D.3.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.3.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.3.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.3.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.3.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.3.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.3.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.3.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.3.9#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.3.10#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.3.11#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.3.12#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.3.13#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.3.14#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.3.15#primary': ownerDomainApproval(),
  // Anhang D.4: fünf Verwaltungsrollen. Fachfrage: Q-D.4-verwaltungsrollen.
  'bbk-babz-2025:D.4.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.4.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.4.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.4.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:D.4.5#primary': ownerDomainApproval(),
  // Anhang E, Teilslice E-a: die 16 Bergungs- und Fachgruppen des THW. Fachfrage: Q-E.1-a-buchstabenkuerzel.
  'bbk-babz-2025:E.1.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.9#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.10#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.11#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.12#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.13#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.14#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.15#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.16#primary': ownerDomainApproval(),
  // Anhang E, Teilslice E-b: Fachzüge, Zugtrupps, Stab und Logistikeinheiten. Eigener Block, weil
  // hier Führungs- und Unterstellungsverhältnisse zur Prüfung stehen, nicht nur Kürzel. Fachfragen:
  // Q-E.1-b-fuehrungsverhaeltnisse, Q-E.1.17-musterblatt, Q-E.1-zugtrupp-ohne-unterstellung,
  // Q-E.1.21-stab-ohne-staerke.
  'bbk-babz-2025:E.1.17#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.18#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.19#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.20#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.21#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.22#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.23#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.24#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.25#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.26#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.27#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.28#primary': ownerDomainApproval(),
  // Anhang E, Teilslice E-c: Trupps, Teams und der Ortsverband. Fachfragen:
  // Q-E.1-c-staerke-aus-kopfgeometrie, Q-E.1.31-sysbr, Q-E.1.37-einrichtung, Q-E.1-c-o-oder-null.
  'bbk-babz-2025:E.1.29#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.30#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.31#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.32#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.33#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.34#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.35#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.36#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.1.37#primary': ownerDomainApproval(),
  // Anhang E, Teilslice E-d: die 21 Landfahrzeuge E.2.1 bis E.2.21. Eigener Block, weil die Fragen
  // hier das **Gerät** und seine Benennung betreffen. Fachfragen: Q-E.2.7-telelader, Q-E.2-bagger-brmg,
  // Q-E.2-kategorie-widerspruch, Q-E.2-bagger-verwechslung, Q-E.2.6-orange-und-thw. Die Kontrastlage
  // von E.2.6 ist gemessen und in `CONTRAST_EXCEPTIONS` entschieden — keine Fachfrage.
  'bbk-babz-2025:E.2.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.9#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.10#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.11#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.12#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.13#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.14#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.15#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.16#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.17#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.18#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.19#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.20#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.21#primary': ownerDomainApproval(),
  // Anhang E, Teilslice E-e: Anhänger und Sonderkörper. Fachfragen:
  // Q-5.1-anhaenger-ein-oder-zwei-raeder, Q-E.2.26-eigenes-grundzeichen, Q-E.2.22-ohne-kuerzel.
  'bbk-babz-2025:E.2.22#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.23#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.24#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.25#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.26#primary': ownerDomainApproval(),
  // Anhang E, Teilslice E-f: die Wasserfahrzeuge. Fachfragen: Q-E.2-wasserfahrzeuge-gleich-i.3,
  // Q-E.2.27-ohne-kuerzel.
  'bbk-babz-2025:E.2.27#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.28#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.29#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.30#primary': ownerDomainApproval(),
  'bbk-babz-2025:E.2.31#primary': ownerDomainApproval(),
  // Anhang F, Teilslice F-a: F.1.1 bis F.1.11 — elf Zeilen für zehn Abschnitte, weil F.1.11 als
  // erster Abschnitt eine Alternativdarstellung führt. F.1.3 hatte im F-a-Stand kein Rezept und kam
  // mit F-b als Carry-in; der Ledger ist mit dem **Manifest** deckungsgleich, nicht mit dem
  // historischen Zuschnitt (`docs/decisions/2026-08-18-anhang-f-zuschnitt.md`). Fachfragen:
  // Q-F-weiss-als-hilfsorganisation, Q-F.1-a-kuerzel, Q-F.1.1-fuenfter-staerkegrad,
  // Q-F.1-seg-verwechslung, Q-F.1.11-alternative.
  'bbk-babz-2025:F.1.1#primary': ownerDomainApproval(),
  // F.1.2: Fachfrage Q-F.1.2-abc-oder-dekon.
  'bbk-babz-2025:F.1.2#primary': ownerDomainApproval(),
  // F.1.4: Fachfrage Q-F.1.4-zwei-fachdienstzeichen.
  'bbk-babz-2025:F.1.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.1.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.1.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.1.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.1.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.1.9#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.1.10#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.1.11#primary': ownerDomainApproval(),
  // Die erste Ledgerzeile des Katalogs, die keine `primary`-Darstellung führt.
  'bbk-babz-2025:F.1.11#alternative': ownerDomainApproval(),
  'bbk-babz-2025:F.1.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.1.12#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.1.12#alternative': ownerDomainApproval(),
  'bbk-babz-2025:F.1.13#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.1.14#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.1.15#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.1.15#alternative': ownerDomainApproval(),
  'bbk-babz-2025:F.1.16#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.1.17#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.1.18#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.1.19#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.1.20#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.1.21#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.1.22#primary': ownerDomainApproval(),
  // Anhang F, Teilslice F-c: Fahrzeuge und Anhänger des Sanitätsdienstes. Fachfragen:
  // Q-F.2-c-alternativen-faehigkeiten, Q-F.2-c-einzelmarken.
  'bbk-babz-2025:F.2.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.2.1#alternative': ownerDomainApproval(),
  'bbk-babz-2025:F.2.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.2.2#alternative': ownerDomainApproval(),
  'bbk-babz-2025:F.2.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.2.3#alternative': ownerDomainApproval(),
  'bbk-babz-2025:F.2.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.2.4#alternative': ownerDomainApproval(),
  'bbk-babz-2025:F.2.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.2.5#alternative': ownerDomainApproval(),
  'bbk-babz-2025:F.2.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.2.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.2.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.2.9#primary': ownerDomainApproval(),
  // Anhang F, Teilslice F-d: die acht Betreuungsfahrzeuge. Fachfrage: Q-F.2-d-formen.
  'bbk-babz-2025:F.2.10#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.2.11#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.2.12#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.2.13#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.2.14#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.2.15#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.2.16#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.2.17#primary': ownerDomainApproval(),
  // Anhang F, Teilslice F-e: elf Platzzeichen auf dem 12-mm-Kreis. Fachfragen: Q-F.3-e-formbegriffe,
  // Q-F.3-abgrenzung-transport.
  'bbk-babz-2025:F.3.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.3.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.3.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.3.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.3.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.3.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.3.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.3.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.3.9#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.3.10#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.3.11#primary': ownerDomainApproval(),
  // Anhang F, Teilslice F-f: die acht verbleibenden Platzzeichen. Fachfrage: Q-F.3-f-kreisformen.
  'bbk-babz-2025:F.3.12#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.3.13#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.3.14#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.3.15#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.3.16#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.3.17#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.3.18#primary': ownerDomainApproval(),
  'bbk-babz-2025:F.3.19#primary': ownerDomainApproval(),
  // Anhang N: neun Fahrzeuge und Anlaufstellen weiterer Träger. Fachfragen: Q-N-traegerzuordnung,
  // Q-N.2-marken.
  'bbk-babz-2025:N.1.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:N.1.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:N.1.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:N.1.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:N.1.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:N.1.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:N.2.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:N.2.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:N.2.3#primary': ownerDomainApproval(),
  // Anhang G: alle 21 Logistikdarstellungen, je eigener Ledgerplatz. Fachfrage: Q-G-weiss-und-marken.
  'bbk-babz-2025:G.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:G.1.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:G.1.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:G.1.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:G.1.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:G.1.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:G.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:G.2.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:G.2.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:G.2.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:G.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:G.3.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:G.3.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:G.3.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:G.3.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:G.3.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:G.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:G.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:G.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:G.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:G.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:H.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:H.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:H.3#primary': ownerDomainApproval(),
  // I-c: Fachfrage Q-I.1-c-weiss-und-einzelbalken.
  'bbk-babz-2025:I.1.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.1.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.1.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.1.4#primary': ownerDomainApproval(),
  // I-e: die Alternative von I.1.9 ist ein eigener Reviewträger. Fachfrage: Q-I.1-e-hilfsorganisation.
  'bbk-babz-2025:I.1.9#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.1.9#alternative': ownerDomainApproval(),
  'bbk-babz-2025:I.1.10#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.1.11#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.1.12#primary': ownerDomainApproval(),
  // I-f: Fachfrage Q-I.1-f-formen.
  'bbk-babz-2025:I.1.13#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.1.14#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.1.15#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.1.16#primary': ownerDomainApproval(),
  // I-d: Fachfrage Q-I.1-d-weisser-koerper.
  'bbk-babz-2025:I.1.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.1.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.1.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.1.8#primary': ownerDomainApproval(),
  // I-g: Fachfrage Q-I.1-g-bedeutung.
  'bbk-babz-2025:I.1.17#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.1.18#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.1.19#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.1.20#primary': ownerDomainApproval(),
  // I-b: Fachfrage Q-I.2-landfahrzeuge.
  'bbk-babz-2025:I.2.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.2.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.2.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.2.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.2.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.2.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.2.7#primary': ownerDomainApproval(),
  // I.3: die elf source IDs werden im Manifesttest lückenlos aus dem Ledger abgeleitet.
  // Fachfrage: Q-I.3-bedeutung.
  'bbk-babz-2025:I.3.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.3.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.3.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.3.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.3.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.3.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.3.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.3.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.3.9#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.3.10#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.3.11#primary': ownerDomainApproval(),
  // I-j: Fachfrage Q-I.4-marken.
  'bbk-babz-2025:I.4.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.4.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.4.3#primary': ownerDomainApproval(),
  // I-k und I.5.4 bis I.5.8: Fachfrage Q-I.5-wasserrettungspersonal.
  'bbk-babz-2025:I.5.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.5.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.5.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.5.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.5.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.5.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.5.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:I.5.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:2.1#primary': ownerDomainApproval(),
  // 2.2 seit LFH-424. Fachfragen: Q-2-hiorg-aus-raster, Q-2-hiorg-farbe-neutral.
  'bbk-babz-2025:2.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:2.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:2.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:2.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:2.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:2.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:2.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.4.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.4.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.4.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.4.4#primary': ownerDomainApproval(),
  // Die fünf Fahrzeugkategorien aus LFH-424. Fachfragen: Q-5.1-kategoriezuordnung,
  // Q-5.1-verbindungsstrich-endpunkte.
  'bbk-babz-2025:5.1.1.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.1.1.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.1.1.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.1.1.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.1.1.6#primary': ownerDomainApproval(),
  // Die beiden Anhängerfahrwerke aus Kapitel 5.1.2. Fachfrage: Q-5.1-anhaenger-ein-oder-zwei-raeder.
  'bbk-babz-2025:5.1.2.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.1.2.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.3.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.3.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.3.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.3.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.3.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.3.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.4.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.4.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.4.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.1.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.1.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.1.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.1.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.1.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.1.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.1.6#alternative': ownerDomainApproval(),
  'bbk-babz-2025:4.1.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.1.7#alternative': ownerDomainApproval(),
  'bbk-babz-2025:4.1.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.1.8#alternative': ownerDomainApproval(),
  'bbk-babz-2025:4.2.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.2.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.2.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.2.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.2.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.5.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.5.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.5.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.5.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.5.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.5.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.5.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.5.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.6.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.6.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.6.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.6.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.6.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.6.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.9#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.10#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.10#alternative': ownerDomainApproval(),
  'bbk-babz-2025:4.7.11#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.12#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.13#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.14#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.15#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.16#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.17#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.18#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.19#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.20#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.21#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.22#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.23#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.24#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.25#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.26#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.27#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.7.28#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.8.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.8.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.8.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.8.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.8.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.8.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.8.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.8.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.8.9#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.8.10#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.8.11#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.8.12#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.8.13#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.8.14#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.8.15#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.8.16#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.9.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.10.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.10.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.10.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.10.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.10.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.10.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:4.10.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.1.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.1.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.1.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.1.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.1.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.1.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.1.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.1.7#alternative': ownerDomainApproval(),
  'bbk-babz-2025:5.8.1.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.1.8#alternative': ownerDomainApproval(),
  'bbk-babz-2025:5.8.1.9#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.1.10#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.1.11#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.1.12#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.1.13#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.1.13#alternative': ownerDomainApproval(),
  'bbk-babz-2025:5.8.1.14#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.1.14#alternative': ownerDomainApproval(),
  'bbk-babz-2025:5.8.2.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.2.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.2.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.2.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.3.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.3.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.3.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.4.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.4.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.4.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.5.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.5.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.5.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.6.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.6.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.6.2#alternative': ownerDomainApproval(),
  'bbk-babz-2025:5.8.6.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.7.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.7.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.7.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.7.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.7.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.7.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.7.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.7.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.7.9#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.7.10#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.8.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.8.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.8.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.8.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.8.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.8.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.8.6#alternative': ownerDomainApproval(),
  'bbk-babz-2025:5.8.8.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.8.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.8.9#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.8.10#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.8.11#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.8.12#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.8.13#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.8.14#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.8.15#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.8.16#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.8.17#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.9.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.9.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.9.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:5.8.9.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.1.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.1.1#alternative': ownerDomainApproval(),
  'bbk-babz-2025:J.1.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.1.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.1.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.1.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.1.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.1.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.1.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.1.8#alternative': ownerDomainApproval(),
  'bbk-babz-2025:J.1.9#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.1.9#alternative': ownerDomainApproval(),
  'bbk-babz-2025:J.1.10#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.1.10#alternative': ownerDomainApproval(),
  'bbk-babz-2025:J.1.11#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.1.11#alternative': ownerDomainApproval(),
  'bbk-babz-2025:J.1.12#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.1.13#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.1.14#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.2.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.2.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.3.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.3.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.3.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.3.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.3.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.3.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.3.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.3.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.3.9#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.3.10#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.3.11#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.3.12#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.3.13#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.3.14#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.3.15#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.4.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.4.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.4.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.4.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.4.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.4.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.4.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.4.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.4.9#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.4.10#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.4.11#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.4.12#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.4.13#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.4.14#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.4.15#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.4.16#primary': ownerDomainApproval(),
  'bbk-babz-2025:J.4.17#primary': ownerDomainApproval(),
  'bbk-babz-2025:K.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:K.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:K.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:K.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:K.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:K.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:K.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:K.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:K.9#primary': ownerDomainApproval(),
  'bbk-babz-2025:K.10#primary': ownerDomainApproval(),
  'bbk-babz-2025:K.11#primary': ownerDomainApproval(),
  'bbk-babz-2025:K.12#primary': ownerDomainApproval(),
  'bbk-babz-2025:K.13#primary': ownerDomainApproval(),
  'bbk-babz-2025:K.14#primary': ownerDomainApproval(),
  'bbk-babz-2025:K.15#primary': ownerDomainApproval(),
  'bbk-babz-2025:K.16#primary': ownerDomainApproval(),
  'bbk-babz-2025:K.17#primary': ownerDomainApproval(),
  'bbk-babz-2025:K.18#primary': ownerDomainApproval(),
  'bbk-babz-2025:L.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:L.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:L.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:L.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:L.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:L.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:L.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:L.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:L.9#primary': ownerDomainApproval(),
  'bbk-babz-2025:L.10#primary': ownerDomainApproval(),
  'bbk-babz-2025:M.1#primary': ownerDomainApproval(),
  'bbk-babz-2025:M.2#primary': ownerDomainApproval(),
  'bbk-babz-2025:M.3#primary': ownerDomainApproval(),
  'bbk-babz-2025:M.4#primary': ownerDomainApproval(),
  'bbk-babz-2025:M.5#primary': ownerDomainApproval(),
  'bbk-babz-2025:M.6#primary': ownerDomainApproval(),
  'bbk-babz-2025:M.7#primary': ownerDomainApproval(),
  'bbk-babz-2025:M.8#primary': ownerDomainApproval(),
  'bbk-babz-2025:M.9#primary': ownerDomainApproval(),
  'bbk-babz-2025:M.10#primary': ownerDomainApproval(),
  'bbk-babz-2025:M.11#primary': ownerDomainApproval(),
  'bbk-babz-2025:M.12#primary': ownerDomainApproval(),
  'bbk-babz-2025:M.13#primary': ownerDomainApproval(),
  'bbk-babz-2025:M.14#primary': ownerDomainApproval(),
} satisfies Record<string, Review>);

export type ManifestDomainReviewKey = keyof typeof MANIFEST_DOMAIN_REVIEWS;

/** Wirft bei einer nicht inventarisierten Manifestzeile statt still ein Sammelreview zu nutzen. */
export function manifestDomainReviewFor(key: string): DeepReadonly<Review> {
  if (!Object.prototype.hasOwnProperty.call(MANIFEST_DOMAIN_REVIEWS, key)) {
    throw new Error(`Kein Fachreview-Ledger-Eintrag für "${key}".`);
  }
  return MANIFEST_DOMAIN_REVIEWS[key as ManifestDomainReviewKey];
}

/** Eigene fachliche Reviewentscheidung je Quelle; technische Reviews bleiben separat. */
export const SOURCE_DOMAIN_REVIEWS = deepFreeze({
  'bbk-babz-2025': ownerDomainApproval(),
  'babz-svg-2025': ownerDomainApproval(),
  'babz-hinweise-2024': ownerDomainApproval(),
  'skk-2010': ownerDomainApproval(),
  'fwdv-100': ownerDomainApproval(),
  'fwdv-800': ownerDomainApproval(),
  'thw-einheiten': ownerDomainApproval(),
  'phjardas-tz': ownerDomainApproval(),
  'din-14033': ownerDomainApproval(),
  'din-13050': ownerDomainApproval(),
  'din-14034-6': ownerDomainApproval(),
  'din-14095': ownerDomainApproval(),
  'arimo-ofl': ownerDomainApproval(),
} satisfies Record<SourceId, Review>);

export function sourceDomainReviewFor(id: SourceId): DeepReadonly<Review> {
  return SOURCE_DOMAIN_REVIEWS[id];
}

/** Auch Profile besitzen einen expliziten Ledgerplatz; heute existiert nur der Bundeskern. */
export const PROFILE_DOMAIN_REVIEWS = deepFreeze({
  bund: ownerDomainApproval(),
} satisfies Record<ProfileId, Review>);

export function profileDomainReviewFor(id: ProfileId): DeepReadonly<Review> {
  return PROFILE_DOMAIN_REVIEWS[id];
}
